import random


list= ['AHRI','ASHE','AZIR','BARD','EKKO','FIZZ','GNAR','GWEN','JHIN','JINX','KAYN','KLED','LULU','NAMI','NUNU','OLAF','ORNN','PYKE','RELL','RYZE','SETT','SHEN','SION','SONA','TAHM','UDYR','YONE','ZERI','AKALI','AMUMU','ANNIE','BRAND','BRAUM','CORKI','DIANA','ELISE','FIORA','GALIO','GAREN','IVERN','JANNA','JAYCE','KARMA','KAYLE','LEONA','MUNDO','NASUS','NEEKO','POPPY','QUINN','RAKAN','RIVEN','SENNA','SHACO','SIVIR','SWAIN','SYLAS','TALON','TARIC','TEEMO','URGOT','VARUS','VAYNE','VIEGO','XAYAH','YASUO','YUUMI','ZIGGS','AATROX','AKSHAN','ANIVIA','DARIUS','DRAVEN','EZREAL','GRAGAS','GRAVES','ILLAOI','IRELIA','JARVAN','KENNEN','LILLIA','LUCIAN','MAOKAI', 'QIYANA','RAMMUS','RENATA','RENGAR','RUMBLE','SAMIRA','SINGED','SORAKA','SYNDRA','THRESH','TWITCH','VEIGAR','VIKTOR','WUKONG','XERATH','YORICK','ZILEAN']
random.shuffle(list)
print(list)